<?php

require_once dirname(__FILE__) . '/../../../components/MyMails.class.php';

/**
 * Test class for MyMails.
 * Generated by PHPUnit on 2012-06-02 at 14:48:23.
 */
class MyMailsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MyMails
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $config=dirname(__FILE__).'/../config/test.php';
        print_r($config);
        $results=  VUserRegistration::model()->findAll();
        print_r($results);
//        $this->object = new MyMails;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MyMails::send
     * @todo Implement testSend().
     */
    public function testSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
